SELECT CODFILIAL,
       DTENT AS DTENTRADA,
       NUMNOTA,
       CODFORNEC,
       FORNECEDOR,
       (SELECT CGC FROM PCFORNEC WHERE CODFORNEC =AFSIS.CODFORNEC) CNPJ,
       COUNT(CODPROD) AS QTPRODNF,
       SUM(QTCONT) AS QTCONTABIL,
       SUM(BASEICMSANTECIPADO) AS BASEICMSANTECIPADO,
       PERICMSANTECIPADO,
       SUM(VLICMSANTECIPADO) AS VLICMSANTECIPADO
 FROM (SELECT E.DTENT,
       E.NUMNOTA,
       F.CODFORNEC,
       F.FORNECEDOR,
       M.CODPROD,
       P.DESCRICAO PRODUTO,
       NVL(M.NBM, P.NBM) NCM,
       E.NUMTRANSENT,
       E.CODFILIAL,
       M.QTCONT,
       ROUND(NVL(MC.BASEICMSANTECIPADO,0) * M.QTCONT,2) BASEICMSANTECIPADO,
       M.PERICMSANTECIPADO,
       ROUND(NVL(MC.VLICMSANTECIPADO,0) * M.QTCONT,2) VLICMSANTECIPADO
FROM PCNFENT E,
     PCPRODUT P,
     PCMOV M,
     PCFORNEC F,
     PCMOVCOMPLE MC 
WHERE P.CODPROD = M.CODPROD
  AND E.NUMTRANSENT = M.NUMTRANSENT
  AND NVL(E.CODFILIALNF, E.CODFILIAL) = M.CODFILIAL 
  AND E.NUMNOTA = M.NUMNOTA
  AND M.NUMTRANSITEM = MC.NUMTRANSITEM(+)
  AND NVL(E.CODFORNECNF, E.CODFORNEC) = F.CODFORNEC 
  AND M.STATUS IN ('A', 'AB')
  AND M.DTCANCEL IS NULL
  AND E.DTCANCEL IS NULL
  AND NVL(P.CESTABASICALEGIS, 'N') = 'S'
  AND M.QTCONT > 0
  AND MC.VLICMSANTECIPADO > 0
  AND E.DTENT BETWEEN :dt1 AND :dt2
  AND NVL(E.CODFILIALNF, E.CODFILIAL) = :CODFILIAL ) AFSIS
  GROUP BY CODFILIAL, DTENT, NUMNOTA, CODFORNEC, FORNECEDOR, PERICMSANTECIPADO
  ORDER BY DTENT, NUMNOTA
