INSERT INTO PCPRODFILIAL
  (CODPROD,
   CODFILIAL,
   CODCOMPRADOR,
   PROIBIDAVENDA,
   FORALINHA,
   REVENDA,
   ESTOQUEIDEAL,
   MULTIPLO,
   CHECARMULTIPLOVENDABNF,
   ACEITAVENDAFRACAO,
   QTMINAUTOSERV,
   QTMINIMAATACADO,
   QTMINIMAATACADOF,
   ATIVO,
   PISCOFINSRETIDO,
   PERPIS,
   PERCOFINS,
   CLASSE,
   CLASSEVENDA,
   CLASSEESTOQUE,
   CODDISPESTRUTURA,
   PCOMREP1,
   PCOMINT1,
   PCOMEXT1,
   ESTOQUEPORSERIE)
  SELECT PCPRODUT.CODPROD,
         PCFILIAL.CODIGO,
         NULL,
         DECODE(PCPRODUT.OBS, 'PV', 'S', 'N') PROIBIDAVENDA,
         DECODE(PCPRODUT.OBS2, 'FL', 'S', 'N') FORADELINHA,
         PCPRODUT.REVENDA,
         0,
         PCPRODUT.MULTIPLO,
         NVL(PCPRODUT.CHECARMULTIPLOVENDABNF, 'N') CHECARMULTIPLOVENDABNF,
         NVL(PCPRODUT.ACEITAVENDAFRACAO, 'N') ACEITAVENDAFRACAO,
         0,
         0,
         0,
         'S',
         NVL(PCPRODUT.PISCOFINSRETIDO, 'N') PISCOFINSRETIDO,
         NULL,
         NULL,
         PCPRODUT.CLASSE,
         PCPRODUT.CLASSEVENDA,
         PCPRODUT.CLASSEESTOQUE,
         0,
         PCPRODUT.PCOMREP1,
         PCPRODUT.PCOMINT1,
         PCPRODUT.PCOMEXT1,
         'N'
    FROM PCPRODUT, PCFILIAL
   WHERE PCFILIAL.CODIGO <> '99'
     AND PCFILIAL.CODIGO IS NOT NULL
     AND PCPRODUT.CODPROD IS NOT NULL
     AND NOT EXISTS
   (SELECT PCPRODFILIAL.CODPROD
            FROM PCPRODFILIAL
           WHERE PCPRODFILIAL.CODPROD = PCPRODUT.CODPROD
             AND PCPRODFILIAL.CODFILIAL = PCFILIAL.CODIGO)
