INSERT INTO PCEST
  (CODFILIAL,
   CODPROD,
   QTEST,
   QTESTGER,
   QTBLOQUEADA,
   QTINDENIZ,
   QTRESERV,
   QTPENDENTE)
  SELECT 1, CODPROD, 0, 0, 0, 0, 0, 0
    FROM PCPRODUT
   WHERE CODPROD >= 316948
     AND CODPROD IS NOT NULL
     AND NOT EXISTS (SELECT DISTINCT CODPROD
            FROM PCEST
           WHERE CODPROD = PCPRODUT.CODPROD
             AND CODFILIAL = 1)
