/*ALTERACOES PCPRODFILIAL*/
SELECT PCLOGCADASTRO.NOMEOBJETO,
       PCLOGCADASTRO.ACAO,
       PCLOGCADASTRO.ROWIDCAMPO,
       REPLACE(PCLOGCADASTRO.VALOROLD, '}', '}' || CHR(13)) VALOROLD,
       REPLACE(PCLOGCADASTRO.VALORNEW, '}', '}' || CHR(13)) VALORNEW,
       PCLOGCADASTRO.MATRICULAUSUARIO,
       PCEMPR.NOME,
       PCLOGCADASTRO.NOMEAPLICACAO,
       PCLOGCADASTRO.DATALOG,
       PCLOGCADASTRO.VERSAOAPLICATIVO,
       PCLOGCADASTRO.ROWID RID,
       ('CODPROD=' || NOMEOBJETO.CODPROD || ', CODFILIAL=' ||
       NOMEOBJETO.CODFILIAL) VALUESPKS
  FROM PCLOGCADASTRO, PCEMPR, PCPRODFILIAL NOMEOBJETO
 WHERE (PCLOGCADASTRO.MATRICULAUSUARIO = PCEMPR.MATRICULA AND
       PCLOGCADASTRO.ROWIDCAMPO = NOMEOBJETO.ROWID(+) AND
       PCLOGCADASTRO.NOMEOBJETO = 'PCPRODFILIAL')
   AND TRUNC(PCLOGCADASTRO.DATALOG) BETWEEN '01-01-2022' AND '31-12-2023'
   and NOMEOBJETO.CODPROD IN (33384);
