SELECT AFSIS.CODPROD,
       AFSIS.DESCRICAO,
       AFSIS.CODAUXILIAR,
       AFSIS.DESCRICAOECF,
       AFSIS.QT QTVENDIDA,
       NVL((SELECT SUM(PCMOV.QT) AS QTPRODUZIDA
             FROM PCMOV
            WHERE PCMOV.DTMOV BETWEEN &DTINI AND &DTFIM
              AND PCMOV.CODFILIAL = &CODFILIAL
              AND PCMOV.CODPROD = AFSIS.CODPROD
              AND PCMOV.CODOPER = 'EP'),
           0) QTPRODUZIDA,
       (SELECT SUM(QTESTGER)
          FROM PCEST
         WHERE CODFILIAL = &CODFILIAL
           AND CODPROD = AFSIS.CODPROD) QTESTOQUEATUAL,
           ( SELECT COUNT(*) QTDE
           FROM PCMOV
          WHERE CODOPER = 'S'
            AND TRUNC(DTMOV) BETWEEN &DTINI AND &DTFIM
            AND DTCANCEL IS NULL
            AND CODFILIAL= &CODFILIAL
            AND CODAUXILIAR = AFSIS.CODAUXILIAR) QTGIROPERIODO,
             ( SELECT COUNT(*) QTDE
           FROM PCMOV
          WHERE CODOPER = 'S'
            AND TRUNC(DTMOV) = TRUNC(SYSDATE)
            AND DTCANCEL IS NULL
            AND CODFILIAL= &CODFILIAL
            AND CODAUXILIAR = AFSIS.CODAUXILIAR) QTGIRODIAATUAL
            
  FROM (SELECT I.CODPROD,
               (SELECT DESCRICAO FROM PCPRODUT WHERE CODPROD = I.CODPROD) DESCRICAO,
               I.CODAUXILIAR,
               NVL((SELECT DESCRICAOECF
                     FROM PCEMBALAGEM
                    WHERE CODFILIAL = &CODFILIAL
                      AND CODAUXILIAR = I.CODAUXILIAR),
                   (SELECT DESCRICAO FROM PCPRODUT WHERE CODPROD = I.CODPROD)) DESCRICAOECF,
               SUM(I.QT) QT
          FROM PCPEDCECF C, PCPEDIECF I
         WHERE 1 = 1
           AND C.CODFILIAL = &CODFILIAL
           AND C.NUMPEDECF = I.NUMPEDECF
           AND C.CONDVENDA IN (1, 2, 3, 7, 9, 14, 15, 17, 18, 19, 98)
           AND C.DTCANCEL IS NULL
           AND C.POSICAO NOT IN ('C')
           AND I.CODPROD IN
               (SELECT CODPROD FROM PCPRODUT WHERE CODEPTO IN (&CODEPTO))
           AND C.DATA BETWEEN &DTINI AND &DTFIM
         GROUP BY I.CODPROD, I.CODAUXILIAR) AFSIS
         
         
         
        
