/*
  Autor: Álvaro Felipe 
  Data: 22/05/2023 10:49:42 (QP5 v5.371) 
  Departamento: Logística
  Solicitante: Melki (Gerente de Logística Dunorte)
*/
SELECT MX.ID_CARREGAMENTO,
       C.CODMOTORISTA,
       PR.NOME,
       C.CODVEICULO,
       UPPER(V.DESCRICAO) VEICULO,
       C.DTSAIDAVEICULO,
       C.NUMNOTAS,
       C.NUMENT,
       C.NUMCID,
       C.CODROTAPRINC,
       (SELECT XP.DESCRICAO
          FROM DUNORTE.PCROTAEXP XP
         WHERE XP.CODROTA = C.CODROTAPRINC) ROTAPRINC,
       L.CODPRACA,
       (SELECT PRA.PRACA
          FROM DUNORTE.PCPRACA PRA
         WHERE PRA.CODPRACA = L.CODPRACA) PRACA,
       MX.ID_CLIENTE,
       L.CLIENTE,
       L.MUNICENT,
       MX.DATA_CHECKIN,
       MX.DATA_INICIO_DESCARGA,
       MX.DATA_TERMINO_DESCARGA,
       TO_CHAR(MX.DATA_INICIO_DESCARGA, 'HH24:MI:SS') INICIODESCARGA,
       TO_CHAR(MX.DATA_TERMINO_DESCARGA, 'HH24:MI:SS') FIMDESCARGA,
       MX.SITUACAO,
       CASE MX.SITUACAO
         WHEN 'CK' THEN
          'CHECKIN'
         WHEN 'DP' THEN
          'DEVOLUCAO PARCIAL'
         WHEN 'DT' THEN
          'DEVOLUCAO TOTAL'
         WHEN 'EN' THEN
          'ENTREGUE'
         WHEN 'FN' THEN
          'FINALIZADA'
         WHEN 'PD' THEN
          'PENDENTE'
         WHEN 'EP' THEN
          'ESPERA'
         WHEN 'RP' THEN
          'RECEBIMENTO PENDENTE'
         WHEN 'SD' THEN
          'SOLICITADA DEVOLUCAO'
         WHEN 'RE' THEN
          'REENTREGA'
         ELSE
          'OUTRA SITUACAO'
       END DESCSITUACAO,
       MX.LATITUDE,
       MX.LONGITUDE
  FROM MXMENTREGAS.MXMP_ENTREGAS MX,
       DUNORTE.PCCARREG          C,
       DUNORTE.PCCLIENT          L,
       DUNORTE.PCEMPR            PR,
       DUNORTE.PCVEICUL          V
 WHERE 1 = 1
   AND MX.ID_CARREGAMENTO = C.NUMCAR
   AND PR.MATRICULA = C.CODMOTORISTA
   AND V.CODVEICULO = C.CODVEICULO
   AND L.CODCLI = MX.ID_CLIENTE
   AND MX.ID_CARREGAMENTO IN (132712)
 ORDER BY MX.DATA_INICIO_DESCARGA ASC
