SELECT P.CODFILIAL,
       P.CODCLI,
       C.CLIENTE,
       P.DUPLIC,
       P.PREST,
       P.CODCOB,
       B.COBRANCA,
       P.VALOR,
       P.VALORORIG,
       P.DTEMISSAO,
       P.DTVENCORIG,
       CASE
         WHEN ((NVL(P.DTRECEBIMENTOPREVISTO, P.DTVENC) > P.DTVENC) AND
              (P.TXPERMPREVISTO > 0)) THEN
          P.DTRECEBIMENTOPREVISTO
         ELSE
          P.DTVENC
       END DTVENC,
       (P.DTVENC-P.DTVENCORIG) DIASPRORROGADOS,
       P.DTLANCPRORROG,
       P.OBS2,
       CASE P.TIPOPRORROG WHEN 'N' THEN 'NEGOCIACAO' WHEN 'E' THEN 'ATRASO ENTREGA' END TIPOPRORROG,
         P.CODFUNCPRORROG
  FROM PCPREST P, PCCOB B, PCCLIENT C, PCUSUARI U, PCSUPERV S, PCFILIAL F
 WHERE B.CODCOB = P.CODCOB
   AND C.CODCLI = P.CODCLI
   AND P.CODUSUR = U.CODUSUR
   AND S.CODSUPERVISOR = U.CODSUPERVISOR
   AND P.CODFILIAL = F.CODIGO
   AND P.DUPLIC IN (SELECT DUPLIC
                      FROM PCLOGCR
                     WHERE ROTINA LIKE '%1231%'
                       AND DATA BETWEEN '&DTINI' AND '&DTFIM')
   AND P.DTPAG IS NULL
   --AND ((P.TIPOPRORROG IN ('E','N')) OR (P.TIPOPRORROG = '&TIPOPRORROG'))
   AND P.TIPOPRORROG IN ()
   AND NVL(P.CODCOBORIG, 'X') <> 'SUPP'
 ORDER BY P.DTVENC, P.CODCLI;

