CREATE TABLE CTRLACESSOLOG (
  DTALTERACAO DATE,
  ALTERACAO VARCHAR2(30),
  TABELA VARCHAR2(30),
  CODROTINA NUMBER(8),
  CODCONTROLE NUMBER(8),
  CODUSUARIO NUMBER(8),
  VALOROLD VARCHAR2(4000),
  VALORNEW VARCHAR2(4000),
  USUARIO VARCHAR2(30),
  MAQUINA VARCHAR2(30),
  PROGRAMA VARCHAR2(30),
  IP VARCHAR2(30)
);