SELECT OSUSER USUARIO
  FROM V$SESSION V
 WHERE USERNAME IS NOT NULL
   AND UPPER(USERNAME) NOT IN
       ('SYSTEM', 'ORACLE', 'DBSNMP', 'SYSMAN', 'SYS')
   AND PROGRAM LIKE '%AFLP9701%'
   AND MACHINE LIKE (SELECT SYS_CONTEXT( 'USERENV', 'HOST' ) FROM DUAL);
